nodeLinker: node-modules
yarnPath: .yarn/releases/yarn-4.9.1.cjs

packageExtensions:
  "@storybook/addon-docs@*":
    peerDependencies:
      "@types/react": "*"
  "@storybook/addon-essentials@*":
    peerDependencies:
      "@types/react": "*"
  "@storybook/react-vite@*":
    peerDependencies:
      typescript: "*"
  "eslint-plugin-storybook@*":
    peerDependencies:
      typescript: "*"
  "storybook-dark-mode@*":
    peerDependencies:
      react: "*"
      react-dom: "*"
      storybook: "*"
  "@storybook/core@*":
    peerDependencies:
      storybook: "*"
