nodeLinker: node-modules
yarnPath: .yarn/releases/yarn-4.9.2.cjs

packageExtensions:
  "@storybook/addon-docs@*":
    peerDependencies:
      "@types/react": "*"
  "@storybook/addon-essentials@*":
    peerDependencies:
      "@types/react": "*"
  "@storybook/core@*":
    peerDependencies:
      storybook: "*"
  "@storybook/react-vite@*":
    peerDependencies:
      typescript: "*"
  eslint-plugin-storybook@*:
    peerDependencies:
      typescript: "*"
  storybook-dark-mode@*:
    peerDependencies:
      react: "*"
      react-dom: "*"
      storybook: "*"
