approvedGitRepositories:
  - "**"

enableScripts: true

nodeLinker: node-modules

npmMinimalAgeGate: 0

packageExtensions:
  "@commitlint/cli@*":
    peerDependencies:
      "@types/node": "*"
      typescript: "*"
  "@commitlint/load@*":
    peerDependencies:
      "@types/node": "*"
      typescript: "*"
  eslint-plugin-storybook@*:
    peerDependencies:
      typescript: "*"
  storybook@*:
    peerDependencies:
      "@testing-library/dom": "*"
      react: "*"
      react-dom: "*"

yarnPath: .yarn/releases/yarn-4.17.1.cjs
