nodeLinker: node-modules
yarnPath: .yarn/releases/yarn-4.12.0.cjs

packageExtensions:
  storybook@*:
    peerDependencies:
      react: "*"
      react-dom: "*"
      "@testing-library/dom": "*"
  "@storybook/addon-docs@*":
    peerDependencies:
      "@types/react": "*"
  "@storybook/react-vite@*":
    peerDependencies:
      typescript: "*"
  eslint-plugin-storybook@*:
    peerDependencies:
      typescript: "*"
  "@commitlint/cli@*":
    peerDependencies:
      "@types/node": "*"
      typescript: "*"
  "@commitlint/load@*":
    peerDependencies:
      "@types/node": "*"
      typescript: "*"
